### ISSUE TITLE
Outdated peer dependency

### ISSUE THREAD

**Issue by zoellner** [yamatatsu/vitest-environment-dynalite#1]
**Describe the bug**
vitest is on v 1.x but this repo still has a 0.x peer dependency.

Dependencies should be updated and a new version released.

**To Reproduce**
`npm i vitest`
`npm i vitest-environment-dynalite`

**Expected behavior**
Can install without conflicts

**Comment by yamatatsu** [comment]
@zoellner 
Thank you so much for your issue! 🙇🏻 
I've fixed it and released v2.0.0 now!
